name: "packages"

on:
  workflow_dispatch:
  issues:
    types: [edited]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: node index.js
