name: "packages"

inputs:
  package:
    description: 'Package name'
    required: true
    default: '@halsp/'
  times:
    description: 'Run times'
    required: true
    default: '1'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: node single.js ${{imports.package}} ${{imports.times}}
