name: "@ipare/cli"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  issues:
    types: [opened, edited, locked, unlocked, deleted]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
      - run: npm i -g yarn --force
      - run: yarn config set registry https://registry.npmjs.org
      - run: yarn global add create-ipare -g
      - run: yarn global add @ipare/cli -g
      - run: ipare create ipare-project -pm yarn -ps inject,router,view,mva,pipe,filter,testing,static,swagger,jwt,validator,env,logger -f --skipEnv -sg -sr
