name: "install all"

on:
  workflow_dispatch:
  issues:
    types: [opened, edited, locked, unlocked, deleted]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/
      - run: npm i -g yarn --force
      - run: yarn config set registry https://registry.npmjs.org
      - run: yarn install
      - run: node install-all.js
